export const timelineData = [
  {
    id: "dev_2025_pilares",
    date: "09/2025 - 10/2025",
    title: "Frontend Developer",
    company: "Fundación Plan Pilares",
    location: "Mendoza",
    modality: "Remote",
    description: "Comprehensive development of a corporate website in WordPress, including technical customization and UX/UI optimization. Ensured responsive design and efficient loading through strategic configuration of plugins and content.",
  },
  {
    id: "dev_2025_mix",
    date: "06/2025 - 09/2025",
    title: "Software Developer",
    company: "Inncome",
    location: "Mendoza",
    modality: "Hybrid",
    description: "I participated in the development of multiple projects, handling frontend tasks with Next.js and backend tasks with Spring.",
  },
  {
    id: "dev_2025_team",
    date: "02/2025 - 03/2025",
    title: "Frontend Developer",
    company: "No Country",
    location: "Buenos Aires",
    modality: "Remote",
    description: "I developed a team management system using React TS, Spring, and MySQL.",
  },
  {
    id: "dev_2023",
    date: "04/2023 - 10/2023",
    title: "Frontend Developer",
    company: "Quinto Impacto Semillero",
    location: "Mendoza",
    modality: "Hybrid",
    description: "I developed responsive interfaces and websites using JS, HTML, and CSS.",
  },
  {
    id: "tech_2020",
    date: "02/2020 - 08/2022",
    title: "Computer Technician",
    company: "Familia Andrada SAS",
    location: "Mendoza",
    modality: "On-site",
    description: `I worked on the installation, configuration, and maintenance of hardware and software.`,
  },
] as const;
